### ANNAPOORNIMA S
## 225229101

## Part-I: Write a method for sigmoid function

###  1. Write a function, mysigmoid(x), that takes the real number x and returns the sigmoid value using math.exp().

In [1]:
import math
def mysigmoid(x):
    return 1 / (1 + math.exp(-x))

### 2.Call mysigmoid() with x=4 and print the sigmoid value of 4.

In [4]:
result = mysigmoid(4)
print(result)

0.9820137900379085


### 3.Now, find the sigmoid values for x=[1, 2, 3]. Observe the results.

In [7]:
x = [1, 2, 3]

sigmoid_values = [mysigmoid(val) for val in x]

print(sigmoid_values)


[0.7310585786300049, 0.8807970779778823, 0.9525741268224334]


### 4. Rewrite mysigmoid() using np.exp() function.

In [19]:
import numpy as np
def mysigmoid(x):
    return 1 / (1 + np.exp(-x))

### 5. Now call your function with x=[1, 2, 3] and observe the results

In [20]:
x = [1, 2, 3]
sig= [mysigmoid(val) for val in x]
print("sigmoid values for x=[1,2,3]:",sig)

sigmoid values for x=[1,2,3]: [0.7310585786300049, 0.8807970779778823, 0.9525741268224334]


## Part-II: Gradient or derivative of sigmoid function

In [22]:
def sig_derivative(s):
    return s * (1 - s)
x = 6
sigm=mysigmoid(x)
gradient = sig_derivative(sigm)
print("Gradient of sigmoid(4):", gradient)


Gradient of sigmoid(4): 0.002466509291359931


## Part-III: Write a method image_to_vector()

In [23]:
#1
import numpy as np

def image_to_vector(image):
    length, height, channels = image.shape
    vector = image.reshape((length * height * channels, 1))
    return vector

# Example usage:
image = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

vector = image_to_vector(image)
print("Vector shape:", vector.shape)
print("Vector:")
print(vector)

Vector shape: (18, 1)
Vector:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]]


In [24]:
#2
import numpy as np

def image_to_vector(image):
    length, height, channels = image.shape
    vector = image.reshape((length * height * channels, 1))
    return vector

# Test with a 3x3x3 array of RGB color values
image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[255, 255, 0], [255, 0, 255], [0, 255, 255]],
    [[128, 128, 128], [64, 64, 64], [192, 192, 192]]
])

vector = image_to_vector(image)
print("Vector shape:", vector.shape)
print("Vector:")
print(vector)


Vector shape: (27, 1)
Vector:
[[255]
 [  0]
 [  0]
 [  0]
 [255]
 [  0]
 [  0]
 [  0]
 [255]
 [255]
 [255]
 [  0]
 [255]
 [  0]
 [255]
 [  0]
 [255]
 [255]
 [128]
 [128]
 [128]
 [ 64]
 [ 64]
 [ 64]
 [192]
 [192]
 [192]]


## Part-IV: Write a method normalizeRows()

In [25]:
import numpy as np

def normalizeRows(x):
    norms = np.linalg.norm(x, axis=1, keepdims=True)
    return x / norms

# Example usage:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

normalized_x = normalizeRows(x)
print("Normalized matrix:")
print(normalized_x)

Normalized matrix:
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]


## Part-V: Multiplication and Vectorization Operations

In [27]:
#1.A
import numpy as np

x1 = np.array([9, 2, 5])
x2 = np.array([7, 2, 2])
multiplication = np.multiply(x1, x2)
print("Multiplication:", multiplication)
dot_product = np.dot(x1, x2)
print("Dot product:", dot_product)

Multiplication: [63  4 10]
Dot product: 77


In [28]:
#B
import numpy as np

x1 = np.array([9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0, 4, 5, 7])
x2 = np.array([7, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 8, 5, 3])
multiplication = np.multiply(x1, x2)
print("Multiplication:", multiplication)
dot_product = np.dot(x1, x2)
print("Dot product:", dot_product)



Multiplication: [63  4 10  0  0 63 10  0  0  0 81  4 25  0  0 32 25 21]
Dot product: 338


In [29]:
#2
import numpy as np
import timeit

N = 1000000   
            
x1 = np.random.rand(N)
x2 = np.random.rand(N)
multiplication_time = timeit.timeit(lambda: np.multiply(x1, x2), number=100)
print("Multiplication Time:", multiplication_time)
vectorization_time = timeit.timeit(lambda: x1 * x2, number=100)
print("Vectorization Time:", vectorization_time)


Multiplication Time: 0.3936325
Vectorization Time: 0.4050125


## Part-VI: Implement L1 and L2 loss functions

In [34]:
import numpy as np
def loss_l1(y, ypred):
    return np.sum(np.abs(y - ypred))
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
l1_loss = loss_l1(y, ypred)
print("L1 Loss:", l1_loss)


L1 Loss: 1.1


In [35]:
#2
import numpy as np
def loss_l2(y, ypred):
    return np.sum((y - ypred) ** 2)
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
l2_loss = loss_l2(y, ypred)
print("L2 Loss:", l2_loss)

L2 Loss: 0.43
